# Generated by Django 4.1.3 on 2022-11-27 07:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("name", models.CharField(max_length=200)),
                (
                    "id",
                    models.UUIDField(
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name=uuid.uuid4,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formula",
            fields=[
                ("title", models.CharField(max_length=200)),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(blank=True, to="formulas_database.tag"),
                ),
            ],
        ),
    ]
