# Generated by Django 4.1.3 on 2022-11-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas_database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
