# Generated by Django 4.1.3 on 2022-11-27 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("formulas_database", "0002_formula_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
