# Generated by Django 4.1.3 on 2022-11-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulas_database", "0003_tag_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="formula",
            name="formula",
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
